export const CompleteJavascriptJonasS = [
  `Course Structure and Projects | JavaScript 🔥 | Lecture 001`,
  `Watch Before You Start! | JavaScript 🔥 | Lecture 002`,
  `Setting Up Our Code Editor | JavaScript 🔥 | Lecture 003`,
  `Section 2 | Fundamental part -1 Intro | JavaScript 🔥 | Lecture 004`,
  `Hello World! | JavaScript 🔥 | Lecture 005`,
  `A Brief Introduction to JavaScript 🔥 | Lecture 006`,
  `Linking a JavaScript File | JavaScript 🔥 | Lecture 007`,
  `Values and Variables | JavaScript 🔥  | Lecture 008`,
  `Data Types | JavaScript 🔥 | Lecture 09`,
  `let, const and var | JavaScript 🔥 | Lecture 010`,
  `Basic Operators | JavaScript 🔥 | Lecture 011`,
  `Operator Precedence | JavaScript 🔥 | Lecture 012`,
  `Coding Challenge #1 | JavaScript 🔥 | Lecture 013`,
  `Strings and Template Literals | JavaScript 🔥 | Lecture 014`,
  `Taking Decisions: if else Statements | JavaScript 🔥 | Lecture 015`,
  `Coding Challenge #2 | JavaScript 🔥 | Lecture 016`,
  `Type Conversion and Coercion | JavaScript 🔥 | Lecture 017`,
  `Truthy and Falsy Values | JavaScript 🔥 | Lecture 018`,
  `Equality Operators == vs === | JavaScript 🔥 | Lecture 019`,
  `Boolean Logic | JavaScript 🔥 | Lecture 020`,
  `Logical Operators | JavaScript 🔥 | Lecture 021`,
  `Coding Challenge #3 |  JavaScript 🔥 | Lecture 022`,
  `The switch Statement | JavaScript 🔥 | Lecture 023`,
  `Statements and Expressions | JavaScript 🔥 | Lecture 024`,
  `The Conditional (Ternary) Operator | JavaScript 🔥 | Lecture 025`,
  `Coding Challenge #4 | JavaScript 🔥 | Lecture 026`,
  `JavaScript Releases: ES5, ES6+ and ESNext | JavaScript 🔥 | Lecture 027`,
  `Section Intro | Fundamental Part 2 | JavaScript 🔥 | Lecture 028`,
  `Activating Strict Mode | JavaScript 🔥 | Lecture 029`,
  `Functions | JavaScript 🔥 | Lecture 030`,
  `Function Declarations vs Expressions | JavaScript 🔥 | Lecture 031`,
  `Arrow Functions | JavaScript 🔥 | Lecture 032`,
  `Functions Calling Other Functions | JavaScript 🔥 | Lecture 033`,
  `Reviewing Functions | JavaScript 🔥 | Lecture 034`,
  `Coding Challenge #5 | JavaScript 🔥 | Lecture 035`,
  `Introduction to Arrays | JavaScript 🔥 | Lecture 036`,
  `Basic Array Operations (Methods) | JavaScript 🔥 | Lecture 037`,
  `Coding Challenge #6 | JavaScript 🔥 | Lecture 038`,
  `Introduction to Objects | JavaScript 🔥 | Lecture 039`,
  `Dot vs Bracket Notation | JavaScript 🔥 | Lecture 040`,
  `Object Methods | JavaScript 🔥 | Lecture 041`,
  `Coding Challenge #7 | JavaScript 🔥 | Lecture 042`,
  `Iteration The for Loop | JavaScript 🔥 | Lecture 043`,
  `Looping Arrays, Breaking and Continuing | JavaScript 🔥 | Lecture 044`,
  `Looping Backwards and Loops in Loops | JavaScript 🔥 | Lecture 045`,
  `The while Loop | JavaScript 🔥 | Lecture 046`,
  `Coding Challenge #8 | JavaScript 🔥 | Lecture 047`,
  `Pathways and Section Roadmaps | JavaScript 🔥 | Lecture 048`,
  `Section 5 Intro | Developer Skills & Editor Setup | JavaScript 🔥 | Lecture 049`,
  `Setting up Prettier and VS Code | JavaScript 🔥 | Lecture 050`,
  `Installing Node.js and Setting Up a Dev Environment | JavaScript 🔥 | Lecture 051`,
  `Learning How to Code | JavaScript 🔥 | Lecture 052`,
  `How to Think Like a Developer: Become a Problem Solver! | JavaScript 🔥 | Lecture 053`,
  `Using Google, StackOverflow and MDN | JavaScript 🔥 | Lecture 054`,
  `Debugging (Fixing Errors) | JavaScript 🔥 | Lecture 055`,
  `Debugging with the Console and Breakpoints | JavaScript 🔥 | Lecture 056`,
  `Coding Challenge #9 | JavaScript 🔥 | Lecture 057`,
  `Section 6  Intro | HTML & CSS Crash Course [OPTIONAL] | JavaScript 🔥 | Lecture 058`,
  `Basic HTML Structure and Elements | JavaScript 🔥 | Lecture 059`,
  `Attributes, Classes and IDs | JavaScript 🔥 | Lecture 060`,
  `Basic Styling with CSS | JavaScript 🔥 | Lecture 061`,
  `Introduction to the CSS Box Model | JavaScript 🔥 | Lecture 062`,
  `Section Intro | JavaScript in the Browser_ DOM and Events Fundamentals | JavaScript 🔥 | Lecture 063`,
  `PROJECT #1: Guess My Number!. | JavaScript 🔥 | Lecture 064`,
  `What's the DOM and DOM Manipulation | JavaScript 🔥 | Lecture 065`,
  `Selecting and Manipulating Elements | JavaScript 🔥 | Lecture 066`,
  `Handling Click Events | JavaScript 🔥 | Lecture 067`,
  `Implementing the Game Logic | JavaScript 🔥 | Lecture 068`,
  `Manipulating CSS Styles | JavaScript 🔥 | Lecture 069`,
  `Coding Challenge #10 | JavaScript 🔥 | Lecture 070`,
  `Implementing Highscores | JavaScript 🔥 | Lecture 071`,
  `Refactoring Our Code: The DRY Principle | JavaScript 🔥 | Lecture 072`,
  `PROJECT #2: Modal Window | JavaScript 🔥 | Lecture 073`,
  `Working With Classes | JavaScript 🔥 | Lecture 074`,
  `Handling an "Esc" Keypress Event | JavaScript 🔥 | Lecture 075`,
  `PROJECT #3: Pig Game | JavaScript 🔥 | Lecture 076`,
  `Rolling the Dice | JavaScript 🔥 | Lecture 077`,
  `Switching the Active Player | JavaScript 🔥 | Lecture 078`,
  `Holding Current Score | JavaScript 🔥 | Lecture 079`,
  `Resetting the Game | JavaScript 🔥 | Lecture 080`,
  `Section 8 Intro | How JavaScript Works Behind the Scenes | JavaScript 🔥 | Lecture 081`,
  `An High-Level Overview of JavaScript | JavaScript 🔥 | Lecture 082`,
  `The JavaScript Engine and Runtime | JavaScript 🔥 | Lecture 083`,
  `Execution Contexts and The Call Stack | JavaScript 🔥 | Lecture 084`,
  `Scope and The Scope Chain | JavaScript 🔥 | Lecture 085`,
  `Scoping in Practice | JavaScript 🔥 | Lecture 086`,
  `Variable Environment: Hoisting and The TDZ | JavaScript 🔥 | Lecture 087`,
  `Hoisting and TDZ in Practice | JavaScript 🔥 | Lecture 088`,
  `The this Keyword | JavaScript 🔥 | Lecture 089`,
  `The this Keyword in Practice | JavaScript 🔥 | Lecture 090`,
  `Regular Functions vs Arrow Functions | JavaScript 🔥 | Lecture 091`,
  `Primitives vs Objects (Primitive vs Reference Types) | JavaScript 🔥 | Lecture 092`,
  `Primitives vs Objects in Practice | JavaScript 🔥 | Lecture 093`,
  `Section 9 Intro | Data Structures Modern Operators and Strings | JavaScript 🔥 | Lecture 094`,
  `Destructuring Arrays | JavaScript 🔥 | Lecture 095`,
  `Destructuring Objects | JavaScript 🔥 | Lecture 096`,
  `The Spread Operator (...) | JavaScript 🔥 | Lecture 097`,
  `Rest Pattern and Parameters | JavaScript 🔥 | Lecture 098`,
  `Short Circuiting (&& and II) | JavaScript 🔥 | Lecture 099`,
  `The Nullish Coalescing Operator (??) | JavaScript 🔥  | Lecture 100`,
  `Logical Assignment Operators | JavaScript 🔥 | Lecture 101`,
  `Coding Challenge #11 | JavaScript 🔥  | Lecture 102`,
  `Looping Arrays: The for-of Loop | JavaScript 🔥 | Lecture 103`,
  `Enhanced Object Literals | JavaScript 🔥 | Lecture 104`,
  `Optional Chaining (?.) | JavaScript 🔥 | Lecture 105`,
  `Looping Objects: Object Keys, Values, and Entries | JavaScript 🔥 | Lecture 106`,
  `Coding Challenge #12 | JavaScript 🔥 | Lecture 107`,
  `Sets | JavaScript 🔥 | Lecture 108`,
  `Maps: Fundamentals | JavaScript 🔥  | Lecture 109`,
  `Maps: Iteration | JavaScript 🔥 | Lecture 110`,
  `Summary: Which Data Structure to Use | JavaScript 🔥 | Lecture 111`,
  `Coding Challenge #13 |  JavaScript 🔥 | Lecture 112`,
  `Working With Strings - Part 1 | JavaScript 🔥 | Lecture 113`,
  `Working With Strings - Part 2 | JavaScript 🔥 | Lecture 114`,
  `Working With Strings - Part 3 | JavaScript 🔥 | Lecture 115`,
  `Coding Challenge #14 | JavaScript 🔥 | Lecture 116`,
  `String Methods Practice | JavaScript 🔥 | Lecture 117`,
  `Section Intro | A Closer Look at Functions | JavaScript 🔥 | Lecture 118`,
  `Default Parameters | JavaScript 🔥 | Lecture 119`,
  `How Passing Arguments Works: Value vs Reference | JavaScript 🔥  | Lecture 120`,
  `First-Class and Higher-Order Functions | JavaScript 🔥 | Lecture 121`,
  `Functions Accepting Callback Functions | JavaScript 🔥 | Lecture 122`,
  `Functions Returning Functions | JavaScript 🔥 | Lecture 123`,
  `The call and apply Methods | JavaScript 🔥 | Lecture 124`,
  `The bind Method | JavaScript 🔥 | Lecture 125`,
  `Coding Challenge #15 |  JavaScript 🔥 | Lecture 126`,
  `Immediately Invoked Function Expressions (IIFE) | JavaScript 🔥 | Lecture 127`,
  `Closures | JavaScript 🔥 | Lecture 128`,
  `More Closure Examples | JavaScript 🔥 | Lecture 129`,
  `Coding Challenge #16  | JavaScript 🔥 | Lecture 130`,
  `Section Intro 11 | Working With Arrays | JavaScript 🔥 | Lecture 131`,
  `Simple Array Methods | JavaScript 🔥 | Lecture 132`,
  `The new at Method | JavaScript 🔥 | Lecture 133`,
  `Looping Arrays_ forEach | JavaScript 🔥 | Lecture 134`,
  `forEach With Maps and Sets | JavaScript 🔥 | Lecture 135`,
  `PROJECT: "Bankist" App | JavaScript 🔥 | Lecture 136`,
  `Creating DOM Elements | JavaScript 🔥 | Lecture 137`,
  `Coding Challenge #17 | JavaScript 🔥 | Lecture 138`,
  `Data Transformations_ map, filter, reduce | JavaScript 🔥 | Lecture 139`,
  `The map Method | JavaScript 🔥 | Lecture 140`,
  `Computing Usernames | JavaScript 🔥 | Lecture 141`,
  `The filter Method | JavaScript 🔥 | Lecture 142`,
  `The reduce Method | JavaScript 🔥 | Lecture 143`,
  `Coding Challenge #18 | JavaScript 🔥 | Lecture 144`,
  `The Magic of Chaining Methods | JavaScript 🔥 | Lecture 145`,
  `Coding Challenge #19 | JavaScript 🔥 | Lecture 146`,
  `The find Method | JavaScript 🔥 | Lecture 147`,
  `Implementing Login | JavaScript 🔥 | Lecture 148`,
  `Implementing Transfers | JavaScript 🔥 | Lecture 149`,
  `The findIndex Method | JavaScript 🔥 | Lecture 150`,
  `Some and Every | JavaScript 🔥 | Lecture 151`,
  `flat and flatMap | JavaScript 🔥 | Lecture 152`,
  `Sorting Arrays | JavaScript 🔥 | Lecture 153`,
  `More Ways of Creating and Filling Arrays | JavaScript 🔥 | Lecture 154`,
  `Summary: Which Array Method to Use | JavaScript 🔥 | Lecture 155`,
  `Array Methods Practice | JavaScript 🔥 | Lecture 156`,
  `Coding Challenge #20 | JavaScript 🔥 | Lecture 157`,
  `Section 12 Intro | Numbers, Dates, Intl and Timers | JavaScript 🔥 | Lecture 158`,
  `Converting and Checking Numbers | JavaScript 🔥 | Lecture 159`,
  `Math and Rounding | JavaScript 🔥 | Lecture 160`,
  `The Remainder Operator | JavaScript 🔥 | Lecture 161`,
  `Numeric Separators | JavaScript 🔥 | Lecture 162`,
  `Working with BigInt | JavaScript 🔥 | Lecture 163`,
  `Creating Dates | JavaScript 🔥 | Lecture 164`,
  `Adding Dates to "Bankist" App | JavaScript 🔥 | Lecture 165`,
  `Operations With Dates | JavaScript 🔥 | Lecture 166`,
  `Internationalizing Dates (Intl) | JavaScript 🔥 | Lecture 167`,
  `Internationalizing Numbers (Intl) | JavaScript 🔥 | Lecture 168`,
  `Timers: setTimeout and setInterval | JavaScript 🔥 | Lecture 169`,
  `Implementing a Countdown Timer | JavaScript 🔥 | Lecture 170`,
  `Section 13 Intro | Advanced DOM and Events | JavaScript 🔥 | Lecture 171`,
  `PROJECT_ _Bankist_ Website | JavaScript 🔥 | Lecture 172`,
  `How the DOM Really Works | JavaScript 🔥 | Lecture 173`,
  `Selecting, Creating, and Deleting Elements | JavaScript 🔥 | Lecture 174`,
  `Styles, Attributes and Classes | JavaScript 🔥 | Lecture 175`,
  `Implementing Smooth Scrolling | JavaScript 🔥 | Lecture 176`,
  `Types of Events and Event Handlers | JavaScript 🔥 | Lecture 177`,
  `Event Propagation_ Bubbling and Capturing | JavaScript 🔥 | Lecture 178`,
  `Event Propagation in Practice | JavaScript 🔥 | Lecture 179`,
  `Event Delegation_ Implementing Page Navigation | JavaScript 🔥 | Lecture 180`,
  `DOM Traversing | JavaScript 🔥 | Lecture 181`,
  `Building a Tabbed Component | JavaScript 🔥 | Lecture 182`,
  `Passing Arguments to Event Handlers | JavaScript 🔥 | Lecture 183`,
  `Implementing a Sticky Navigation_ The Scroll Event | JavaScript 🔥 | Lecture 184`,
  `A Better Way_ The Intersection Observer API  JavaScript 🔥 | Lecture 185`,
  `Revealing Elements on Scroll | JavaScript 🔥 | Lecture 186`,
  `Lazy Loading Images | JavaScript 🔥 | Lecture 187`,
  `Building a Slider Component_ Part 1 | JavaScript 🔥 | Lecture 188`,
  `Building a Slider Component_ Part 2 | JavaScript 🔥 | Lecture 189`,
  `Lifecycle DOM Events | JavaScript 🔥 | Lecture 190`,
  `Efficient Script Loading_ defer and async | JavaScript 🔥 | Lecture 191`,
  `Section 14 Intro | Object-Oriented Programming (OOP) With JavaScript 🔥 | Lecture 192`,
  `What is Object-Oriented Programming JavaScript 🔥 | Lecture 193`,
  `OOP in JavaScript 🔥 | Lecture 194`,
  `Constructor Functions and the new Operator | JavaScript 🔥 | Lecture 195`,
  `Prototypes | JavaScript 🔥 | Lecture 196`,
  `Prototypal Inheritance and The Prototype Chain | JavaScript 🔥 | Lecture 197`,
  `Prototypal Inheritance on Built-In Objects | JavaScript 🔥 | Lecture 198`,
  `Coding Challenge #21 | JavaScript 🔥 | Lecture 199`,
  `ES6 Classes | JavaScript 🔥 | Lecture 200`,
];
